name: usdt_vault
description: "Offline-first TRON USDT wallet with 3-password encryption, local biometrics, and email export."
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cryptography: ^2.7.0
  http: ^1.2.1
  bs58check: ^1.0.2
  web3dart: ^2.7.3
  pointycastle: ^3.7.3
  share_plus: ^9.0.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.3
  uuid: ^4.4.2
  convert: ^3.1.1
  mobile_scanner: ^3.5.7   # 二维码/条码扫描
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  mailer: ^6.5.0
  http_parser: ^4.1.2
  local_auth: ^2.1.7  # 或兼容你当前 Flutter 版本的最新 2.x
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  # 可选：Android 自适应图标（前景/背景分层）
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  min_sdk_android: 23